/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cl.Hack.Consolas.GUI;

import Cl.Hack.Consolas.Conf.Confi;
import Cl.Hack.Consolas.FUN.Directorio;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author march
 */
public class FrHomePS3 extends javax.swing.JFrame {

    Directorio d = new Directorio();
    static String urlUSB;
    /**
     * Creates new form FrHomePS3
     */
    public FrHomePS3() {
        initComponents();
        USB();
        jButton1.setEnabled(false);
        jtaMensaje.setEditable(false);
    }

    public void USB(){
        File unidades[] = File.listRoots();
        jcbUSB.removeAllItems();
        for(int i=0;i<unidades.length;i++){
//            System.out.println(unidades[i]);
            System.out.println(FileSystemView.getFileSystemView().getSystemDisplayName (unidades[i]));
            jcbUSB.addItem(FileSystemView.getFileSystemView().getSystemDisplayName (unidades[i]));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensaje = new javax.swing.JTextArea();
        txtUSB = new javax.swing.JLabel();
        jcbUSB = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Crear Carpetas en USB:");

        jButton1.setText("Carpetas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtaMensaje.setColumns(20);
        jtaMensaje.setRows(5);
        jScrollPane1.setViewportView(jtaMensaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );

        txtUSB.setText("jLabel2");

        jcbUSB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Seleccionar USB");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbUSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(txtUSB)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUSB)
                    .addComponent(jcbUSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensaje ="";
        mensaje="Carpetas Creadas:";
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Update);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Backup);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PartidasPS3);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Temas);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Musica);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Imagene);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Video);
        
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Exdata);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Games);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Packages);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PS2ISO);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PS3ISO);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PSPSavedata);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PSPISO);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PSXISO);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3ROMS);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3USERLIST);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PS2SD);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3PSV);
        
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Atari2600);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3GameBoy);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3GameBoyColor);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3GameBoyAdvance);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3NintendoNes);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3SuperNintendoSNES);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3SegaGameGear);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3SegaMasterSystem);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3SegaMEgaDriveGenesis);
        mensaje=mensaje+"\n"+d.crearDirec(urlUSB,Confi.PS3Mame);
//        d.copiarArchivo(Confi.InfoImgPs3,urlUSB);
        jtaMensaje.setText(mensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String usbselect=(String) jcbUSB.getSelectedItem();
        String usbselect2=usbselect.substring(usbselect.length() - 4);
        urlUSB=usbselect2.replaceAll("[()]","");
//        txtUSB.setText("Unidad USB Seleccionada "+usbselect);
        txtUSB.setText(usbselect);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrHomePS3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrHomePS3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrHomePS3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrHomePS3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrHomePS3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbUSB;
    private javax.swing.JTextArea jtaMensaje;
    private javax.swing.JLabel txtUSB;
    // End of variables declaration//GEN-END:variables
}
